name: pulzion
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  numberpicker: ^1.2.1
  flutter_statusbarcolor: ^0.2.3
  intl: ^0.16.1
  flutter_svg: ^0.19.2+1
  flutter_downloader: ^1.5.2
  url_launcher: ^5.4.5
  clipboard: ^0.1.2+8
  cached_network_image: ^2.0.0
  firebase_dynamic_links: ^0.5.0+11
  share: ^0.6.4+3
  google_maps_place_picker: ^0.9.4
  google_maps_flutter: ^0.5.25+3
  place_picker: ^0.9.14
  maps_launcher: ^1.2.2+2
  geoflutterfire: ^2.0.3+4
  geolocator: ^5.3.1
  firebase_messaging: ^5.1.2
  font_awesome_flutter: ^8.5.0
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.12.9+6
  google_sign_in: ^4.1.1
  intl_phone_number_input: ^0.2.0
  flare_splash_screen:
  introduction_screen: ^1.0.7
  shared_preferences: ^0.5.12+4
  after_layout: ^1.0.7+2
  flutter_spinkit: ^4.1.2
  transformer_page_view:
  carousel_pro: ^1.0.0
  razorpay_flutter: 1.1.1
  polygon_clipper: ^1.0.2
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  file_picker: 1.4.3+1
  firebase_storage: ^3.1.1
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.0.4
  paytm: ^1.0.0
  upi_india: ^1.1.1
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo2.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/child/
    - assets/images/ngo/

  fonts:
    - family: Acme
      fonts:
        - asset:  assets/fonts/Acme-Regular.ttf
          weight: 600
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf 
          weight: 200   
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: EastSeaDokdo
      fonts:
        - asset: assets/fonts/EastSeaDokdo-Regular.ttf
          weight: 700

